### ISSUE TITLE
Autocomplition does not work for submodules

### ISSUE THREAD

**Issue by mstefuca** [altairengineering/HyperWorksPyAPI#1]
For top level modules, like hm, hw, the autocompletion works okay. But for submodules like hw.hv, hw.hg or hm.entities, the autocompletion is broken after the recent Pylance update.

**Comment by dtolis1999** [comment]
Thank you @mstefuca  for your question we have observed it and we are working on resolving it. 

Please, if you want to use our extension please downgrade Pylance to 2024.7.1 or lower version.
I will update when we resolve the issue.
Thank you!
